sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull php:7.0-cli

script:
    - php -v 
    - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs tests --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
