name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
        composer: ["", "--prefer-lowest"]
    
    steps:
    - uses: actions/checkout@v1
    - name: Change PHP version
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
    - name: Install mailparse
      run: sudo apt install php-mailparse
    - name: Composer install
      run: composer update ${{ matrix.composer }} --no-progress
    - name: PHP Version
      run: php -v
    - name: PhpUnit
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml -c phpunit.xml.dist --whitelist src
    - name: PHPCS
      run: |
        ./vendor/bin/phpcs src --standard=psr2
        ./vendor/bin/phpcs tests --standard=psr2
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: BS4E6dtQa8fUMHQiOTFbQICA6ydxSqkRt
      run: ./vendor/bin/php-coveralls -v
     
