name: CI

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Composer install
      run: composer update --no-progress --ignore-platform-reqs
    - name: PHPCS
      run: |
        composer require friendsofphp/php-cs-fixer  --ignore-platform-reqs
        ./vendor/bin/php-cs-fixer fix src 
        ./vendor/bin/php-cs-fixer fix tests
    - name: Auto Commit
      run: |
        git remote set-url origin https://eXorus:${{ secrets.TADA }}@github.com/php-mime-mail-parser/php-mime-mail-parser
        git config --global user.email "you@example.com"
        git config --global user.name "PHP CS Fixer"
        git checkout auto-commit
        git add src
        git add tests
        git commit -m "PHP CS Fixer" || echo "No changes found. Nothing to commit."
        git push
        
